version: "3.0"
services:
  broker:        # name of the broker
    image: eclipse-mosquitto
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
  nginx:
    image: nginx
    ports:
      - 9999:80
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
